<?php /* vim: set ft=html et ts=2 sw=2: : */ ?>
</section>
<footer>
  <nav class="fullscreen">
    <ul>
      <li><a href="//php.net/copyright">Copyright © 2001-2013 The PHP Group</a></li>
      <li><a href="//php.net/site">Other PHP.net sites</a></li>
      <li><a href="//php.net/privacy">Privacy policy</a></li>
    </ul>
  </nav>
</footer>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery.autocomplete.min.js"></script>
    <script type="text/javascript" src="js/userlisting.php"></script>
    <script type="text/javascript" src="js/search.js"></script>
</body>
</html>
